### ISSUE TITLE
Need to export environment valuables for "Enable Github oAuth with Che"

### ISSUE THREAD

**Issue by danieloh30** [kameshsampath/che-bootializr#2]
In my case, it needs to add export command explicitly for adding env. variables as below.

export CHE_OAUTH_GITHUB_CLIENTID=xxxx
export CHE_OAUTH_GITHUB_CLIENTSECRET=xxxx
export ENABLE_GITHUB_SCRIPT_URL=https://raw.githubusercontent.com/workspace7/cloud-workspaces/master/scripts/enable_github_oauth.sh

curl -fsSL ${ENABLE_GITHUB_SCRIPT_URL} -o ./enable_github_che.sh
bash ./enable_github_che.sh

**Comment by kameshsampath** [comment]
yes that needs to be done manually, if you don't have it will report error

**Comment by danieloh30** [comment]
I'm meaning there is no "export" command in docs. Makes sense?

**Comment by kameshsampath** [comment]
ok .. will add them

**Comment by kameshsampath** [comment]
just now checked the doc it says you have to set those env variables
