### ISSUE TITLE
What is exact Homepage url and Authorization callback URL for Registering OAuth Apps?

### ISSUE THREAD

**Issue by danieloh30** [kameshsampath/che-bootializr#4]
In order to follow up on https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/registering-oauth-apps/, what is $subject?

**Comment by kameshsampath** [comment]
oAuth apps in what ?

**Comment by kameshsampath** [comment]
this is out of topic for this app, but for the call back if you are running che in minishift then it will be like `http://che-eclipse-che.192.168.64.8.nip.io/wsmaster/api/oauth/callback` - replace the `che-eclipse-che.192.168.64.8.nip.io` with your che openshift route

**Comment by danieloh30** [comment]
what is the homepage url? is that master url of minishift for this case?
