### ISSUE TITLE
Error during "./mvnw clean fabric8:deploy"

### ISSUE THREAD

**Issue by danieloh30** [kameshsampath/che-bootializr#5]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Initializr .................................. SKIPPED
[INFO] Spring Initializr :: Generator ..................... SKIPPED
[INFO] Spring Initializr :: Web ........................... SKIPPED
[INFO] Spring Initializr :: Actuator ...................... SKIPPED
[INFO] Spring Initializr :: Docs .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.610 s
[INFO] Finished at: 2017-10-04T23:25:28+09:00
[INFO] Final Memory: 20M/187M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'fabric8' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/daniel/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by kameshsampath** [comment]
`./mvnw clean fabric8:deploy` that is applicable only for fmp enabled plugin for other its just `mvn clean install`

**Comment by kameshsampath** [comment]
also its worth you adding these lines in ~/.m2/settings.xml
```
...
<pluginGroups>
    <pluginGroup>io.fabric8</pluginGroup>
    <pluginGroup>org.springframework.boot</pluginGroup>
  </pluginGroups>
...
```
